### ISSUE TITLE
bug: Error processing argument at index 2, conversion failure from 

### ISSUE THREAD

**Issue by B3718** [tiddly-gittly/TiddlyGit-Desktop#75] opened 2021-07-05 12:51 UTC
```
TypeError: Error processing argument at index 2, conversion failure from 
    at Object.normal (electron/js2c/browser_init.js:81:444)
    at Object.insertItemByType (electron/js2c/browser_init.js:81:1392)
    at Object.a.insert (electron/js2c/browser_init.js:81:3975)
    at Object.a.append (electron/js2c/browser_init.js:81:3639)
    at electron/js2c/browser_init.js:81:5650
    at Array.forEach (<anonymous>)
    at Function.a.buildFromTemplate (electron/js2c/browser_init.js:81:5600)
    at new MenuItem (electron/js2c/browser_init.js:73:587)
    at electron/js2c/browser_init.js:81:5657
    at Array.forEach (<anonymous>)
    at Function.a.buildFromTemplate (electron/js2c/browser_init.js:81:5600)
    at Ie.buildMenu (C:\Users\xfxgj\AppData\Local\TiddlyGit\app-0.4.0\resources\app.asar\.webpack\main\index.js:2:1591012)
```

---

TiddlyGit 0.4.0
Electron 12.0.6
win32 10.0.19042
Locale: zh-CN

**Comment by linonetwo** [comment] 2021-07-05 15:06
Wow， this still happen on latest pre-release 4.0.1-axxx?

**Comment by linonetwo** [comment] 2021-07-09 17:54
Fixed in https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.1-a15

**Closed by linonetwo** 2021-07-09 17:54 UTC

**Comment by linonetwo** [comment] 2021-08-07 13:27
Oh, this is caused by:

```json
{ "label": null, "role": "quit" }
```

in a submenu:

<img width="499" alt="截屏2021-08-07 下午9 21 48" src="https://user-images.githubusercontent.com/3746270/128601671-9d6313cd-2cd7-4572-897b-8b99b9b083d7.png">

which is generated by:

```ts
{ label: () => i18next.t('ContextMenu.Quit') + i18next.t('Menu.TiddlyGit'), role: 'quit' },
```

**Comment by linonetwo** [comment] 2021-12-26 06:28
P.S. this is not resolved. I've just try catch the error, and only log it to the disk.
